### ISSUE TITLE
decimals not shown correctly

### ISSUE THREAD

**Issue by oigroigm** [Tomcuzz/homebridge-tasmota-sonoff-thermostat#1]
the decimals of the temperature displayed in the homekit are always ", 0"

**Comment by Tomcuzz** [comment]
Ah yes now you mention that I have noticed that, think it may be to download with the way I'm storing the temperature. I'll have a look into this and update once I have a fix.

**Comment by Tomcuzz** [comment]
One thing you may want to try in the meantime is in the config setting "start_temperature" to something with a decimal place is 10.1

**Comment by oigroigm** [comment]
I tried but always displays 10,0

**Comment by Tomcuzz** [comment]
Ok so think Ive tracked the problem down to:
https://github.com/Tomcuzz/homebridge-tasmota-sonoff-thermostat/blob/e13e4c2512002248c6be9d6fefea890a5ecdfafe/index.js#L112
Think this line should be 0.1 not 1, will test this out

**Comment by oigroigm** [comment]
I tried the change and now the decimals are rounded to 0.5

**Comment by Tomcuzz** [comment]
So after a bit of digging It looks like 0.5 increments are the smallest homekit can handle in iOS 12  
(https://www.reddit.com/r/HomeKit/comments/8yo9dz/05c_option_for_thermostats/)

Ill put the change into the code base to allow for the 0.5 resolution.

**Comment by Tomcuzz** [comment]
This is now published to NPM so will close this out, feel free to reopen if you have further issues :)
